v2

diff --git a/.github/workflows/frosti.yml b/.github/workflows/frosti.yml
--- a/.github/workflows/frosti.yml
+++ b/.github/workflows/frosti.yml
@@ -33,15 +33,18 @@ jobs:
             az account show
             brew update
             brew install CirroBuild/tap/frosti
-            myAppNames=`frosti provision -s 8850fa2d-2fec-446e-81ce-0866bd59fc04 -r github -e ppe -n cytology | grep -E 'WebAppName|FunctionAppName'`
+            myAppNames=`frosti provision -s 8850fa2d-2fec-446e-81ce-0866bd59fc04 -r github -e ppe -n cytology | grep -E 'WebAppName|FunctionAppName|Error'`
             echo $myAppNames
             myWebApp=`echo $myAppNames | grep WebAppName | sed -e 's/WebAppName://g'`
             myFunctionApp=`echo $myAppNames | grep FunctionAppName | sed -e 's/FunctionAppName://g'`
+            errors=`echo $myAppNames | grep Error | sed -e 's/Error://g'`
+            echo "ERRORS=$errors" >> $GITHUB_OUTPUT
             echo "WEB_APP_NAME=$myWebApp" >> $GITHUB_OUTPUT
             echo "FUNCTION_APP_NAME=$myFunctionApp" >> $GITHUB_OUTPUT
-            
-      - name: Display
-        run: echo "${{ steps.run-frosti.outputs.WEB_APP_NAME }}"
+        
+      - name: Fail
+        if: steps.run-frosti.outputs.ERRORS != null && steps.run-frosti.outputs.ERRORS != ''
+        run: exit 1
             
   DeployDotNet:
     runs-on: macos-latest
